### ISSUE TITLE
Headlines rendered as normal text

### ISSUE THREAD

**Issue by X4fyr** [stefan-niedermann/OwnCloud-Notes#37] opened 2015-12-31 15:12 UTC
First of all, I don't know if this is a bug or a feature.
All my headlines are formatted as normal text, except for extra spacing.
This negates the benefit of multiple level of headlines, as they all look the same.

Greetings,
X4fyr

**Comment by stefan-niedermann** [comment] 2016-01-01 11:32
Thank you for reporting. This is a bug. I would say it's a duplicate of #24 since this seems to be caused by the upstream bypass library.

**Comment by stefan-niedermann** [comment] 2016-01-02 14:18
Should be fixed on master-branch.

**Closed by stefan-niedermann** 2016-01-02 14:18 UTC
Labels: Bug, Duplicate
