### ISSUE TITLE
wrong url error -> crash

### ISSUE THREAD

**Issue by tchncs** [stefan-niedermann/OwnCloud-Notes#36] opened 2015-11-03 19:41 UTC
Hi, i tryed to build your app in Android Studio.
Maybe i did something wrong:

I opened it in Android Studio, and had simply built it with a self created Key.
Than i simply installed it in Android 5.1.1 and tryed to connect to my ownCloud 8.2.0.

In the first try, there will happen nothing if i click on *ok*.
Than, i re-open the App, the *ok*-Button is still dead, but the *enter*-Button on the Keyboard works.
There come a Toast-Notify with *invalid Url* (no sure if its called so in english) and the App crashes.
I had tryed the base Url of my instance and the one, called in the Api documentation also.

The base Url is working fine in MyOwnNotes.
...maybe you want to host us an .apk File?
Not anyone interested on your app, have the experience or pleasure to figure out how this works... :-)

**Comment by stefan-niedermann** [comment] 2015-11-05 18:36
Hi there,

> ...maybe you want to host us an .apk File?
Not anyone interested on your app, have the experience or pleasure to figure out how this works... :-) 

Yeah, would be okay for me. i will check a compiled version in the next days.

Could you maybe contact me via E-Mail and provide me more information (e. g. the url you are trying to use as base url)? stefan.niedermann@googlemail.com
Did you use the latest tagged version or the master branch? the latest tagged version has some bugs which are fixed in master already.

**Comment by tchncs** [comment] 2015-11-06 10:56
Hi, thank you for your answer - i dont think its a problem to write it public :)
Yes, it was the latest, tagged one, and, no joking it worked last night until this day until it started to the next crash loops. (I didnt changed anything, no restart, no nothing)
However, then it started again - now i built from the latest commit, 
look a way better now, the hole app, nice work ;)
Its a very fresh install until now but looks stable this time.

The base Url i mean is just ```cloud2.tchncs.de``` with and without ```https://```.
>  I had tryed the base Url of my instance and the one, called in the Api documentation also.

I also tryed something like ```https://cloud2.tchncs.de/index.php/apps/notes/api/v0.2/```
****
If you want, i had created [this](https://cloud2.tchncs.de/index.php/s/epTZ9Uf9IRPUU1B) ownCloud folder.
Until you got your own download solution/f-droid this folder can be used.
I can create one on an Index also :)
(And of curse i will delete it if you want)

**Comment by tchncs** [comment] 2015-11-06 13:40
**Update:** i played a little around with the Markdown Syntax... after a few trys to create a <hr> or <hx> i ran into a crash loop. I wiped the appdata, re-login and cant reproduce it. Still working.

**Comment by stefan-niedermann** [comment] 2015-11-08 13:41
i think the actual issue "wrong url error -> crash" is solved in master, so i would close it. if you want you can open further issues for other problems.
I think the hr-problem is linked to https://github.com/stefan-niedermann/OwnCloud-Notes/issues/24 and caused by the used upstream library bypass and its integration.

**Closed by stefan-niedermann** 2015-11-08 13:41 UTC

**Comment by stefan-niedermann** [comment] 2016-01-02 17:58
Hi @tchncs,
> If you want, i had created this ownCloud folder.
> Until you got your own download solution/f-droid this folder can be used.

I liked your idea very much, so i adapted it and mention it in the README.md.
Check it out: https://github.com/stefan-niedermann/OwnCloud-Notes/blob/master/README.md

You can find the stable version "release-v0.4.0" and the developer version "app-debug.apk" there.
http://owncloud.niedermann.it/index.php/s/BOM5V1VZwscFk1k

Best regards

**Comment by tchncs** [comment] 2016-01-03 11:14
Oh, thats very nice! :+1:
