### ISSUE TITLE
On first sync all existing notes are removed when server app is installed after client app has been used

### ISSUE THREAD

**Issue by dolohow** [stefan-niedermann/OwnCloud-Notes#131] opened 2016-09-09 07:36 UTC
**Android version:** 5.1

**Device**: Meizu MX4

**System language**: Polish

**App version:** 0.8.1

**App source:** F-Droid

**Steps to reproduce:**
  1. open the app
  2. create new notes
  3. install notes on owncloud instance
  4. at first synchronization all notes are removed

I guess there is no way to get them back?

**Comment by stefan-niedermann** [comment] 2016-09-09 07:39
first of all, let me excuse. Did you have a look at you next/owncloud "deleted files"? Since the notes are stored as normal files at your owncloud you might have a chance to put them out of the trashbin.

**Comment by dolohow** [comment] 2016-09-09 07:40
I used Android app for like a week and I did not have a notes installed on my ownCloud instance, but today I want it to synchronize with my computer so I installed owncloud notes and the Android client removed all _local_ notes.

**Comment by stefan-niedermann** [comment] 2016-09-09 07:42
oh damn, i'm afraid there is no way to recover the notes, sorry. the current master should handle a missing server-app, cold comfort: this will not happen with new versions of the app. :(

**Comment by dolohow** [comment] 2016-09-09 07:44
Damn, I hope I have a good memory.

**Comment by stefan-niedermann** [comment] 2016-09-09 07:45
sorry guy... :confused:

**Comment by dolohow** [comment] 2016-09-09 07:46
I would rather keep that issue open, so other could see it and to track the progress. What do you think?

**Comment by stefan-niedermann** [comment] 2016-09-09 07:49
I will try to reproduce this this weekend, like i said it should be fixed in current master and not happen again when the next version will be published. i can let it open as documentation until 0.9.0 appears

**Comment by dolohow** [comment] 2016-09-09 07:50
Thanks, have a good day.

**Comment by stefan-niedermann** [comment] 2016-09-14 05:49
Just tested with the current master and a disabled server-app. i can not save the settings and therefore not create notes when the server app is not installed. error message says "Login failed. Is the ownCloud Notes App activated?"

**Closed by stefan-niedermann** 2016-09-14 05:49 UTC
