### ISSUE TITLE
Scroll: bar and automatic go to the top

### ISSUE THREAD

**Issue by moshpirit** [stefan-niedermann/OwnCloud-Notes#105] opened 2016-03-27 09:45 UTC
1. A scroll bar would be appreciated
2. The automatic going to the top is quite annoying, is it possible to disable it? 

Thanks a lot!

**Comment by stefan-niedermann** [comment] 2016-03-27 10:33
> The automatic going to the top is quite annoying, is it possible to disable it?

This is a bug in 0.8.0 that is caused by recreating the list after synchronisation has finished. It will be fixed in 0.8.1 which should be released within the next few days.

**Comment by moshpirit** [comment] 2016-03-27 10:44
Cool, thank you!

**Closed** 2016-03-30 10:30 UTC
Labels: New Feature

**Comment by stefan-niedermann** [comment] 2016-03-30 10:31
going to the top is fixed in 0.8.1 (on F-Droid in a few days), scrollbar will be added in 0.9.0 (will take some time).

**Comment by moshpirit** [comment] 2016-03-30 10:52
Cool, thanks!!
