### ISSUE TITLE
Line breaks ignored

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#24] opened 2015-10-23 04:13 UTC
It seems that line breaks are ignored, or turned into simple spaces sometimes.

**Comment by jancborchardt** [comment] 2015-10-24 20:27
The same issue occurs in the widget. Line breaks are not preserved. This makes for a very strange reading and editing experience, actually looking broken and making me not sure if I should use the app on that note in order to not mess up formatting completely.
It’s one of the biggest remaining issues atm @stefan-niedermann :)

**Comment by stefan-niedermann** [comment] 2015-10-25 08:37
Seems to be a problem with the upstream library bypass. @jancborchardt can you give me precise steps to reproduce this bug so i can file an issue to upstream lib?

**Comment by jancborchardt** [comment] 2015-10-25 09:42
Basically, just have any plain text note with line breaks in it. Like this:

> Some text
> Some more text
> 
> Bla

Will appear as:

> Some text Some more text
> 
> Bla

**Comment by stefan-niedermann** [comment] 2016-01-02 14:57
This issue has been reported to the upstream-project: https://github.com/Uncodin/bypass/issues/197

I am sorry, but think, we can only wait and hope that they will fix it.

**Comment by moshpirit** [comment] 2016-01-29 10:00
Same error here, maybe because of markdown? I think there should be an option to enable and disable the MarkDown view (which is already enabled)

**Comment by stefan-niedermann** [comment] 2016-02-09 11:44
There is maybe [a fix](http://meta.stackexchange.com/a/40978) - special thanks to @9662. I will implement this and maybe we finally get a solution here soon.

**Comment by stefan-niedermann** [comment] 2016-02-09 17:28
Very hard, i thought, adding two spaces at the end of every line would do the job (`s.replace("\n", "  \n")`), but this causes empty lines between every list item of lists.

![bildschirmfoto vom 2016-02-09 18 25 41](https://cloud.githubusercontent.com/assets/4741199/12924497/b9035a50-cf5a-11e5-9db9-a59bcf5cdf43.png)

So this is the question: "Quick fix" with causing empty lines or keep it like it is.

(Manual workaround: Add two empty spaces at the lines where you want to have a line break)

**Comment by stefan-niedermann** [comment] 2016-02-09 17:40
Hm. i will keep it as it is to prevent higher damage^^. I'm looking for a new MarkDown library, [pegdown](https://github.com/sirthias/pegdown/) seems to be alive. It's a shame, nearly every MarkDown library like MarkdownJ, JMD etc. seems to be dead... Another option would be MarkDownView.

**Comment by stefan-niedermann** [comment] 2016-02-10 19:30
Finally fixed in 0.8.0.

**Closed** 2016-02-10 19:29 UTC
Labels: Bug, Upstream :: ByPass

**Comment by jancborchardt** [comment] 2016-02-11 13:36
Nice! :) New library, or how did you do it?

**Comment by stefan-niedermann** [comment] 2016-02-11 14:10
Nah :disappointed:, fixed the upstream bug for the moment in my code for now... Not nice, but at least this bug is fixed for the moment...

It's the fix i mentioned [above](https://github.com/stefan-niedermann/OwnCloud-Notes/issues/24#issuecomment-181970277) with exceptions for lists.
```java
StringBuilder sb = new StringBuilder();
for (String line : s.split("\n")) {
  sb.append(line);
  // If line is not a list item
  if (!line.trim().matches("^([\\-*]|[0-9]+\\.)(.)*")) {
    sb.append("  ");
  }
  sb.append("\n");
}
return bypass.markdownToSpannable(sb.toString());
```
